version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mangaverse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ../apps/api
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/mangaverse
      - JWT_SECRET=devsecret
    ports:
      - "4000:4000"

  web:
    build: ../apps/web
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://api:4000/api/v1
    ports:
      - "3000:3000"

volumes:
  pgdata:
